name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  static:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    uses: Jungle-Grid/.github/.github/workflows/reusable-static-pr-ci.yml@b003261dd69d3bd6b7ccba147e1fddca5f8c5e2f
    permissions:
      contents: read
    with:
      working-directory: "."
      run-secret-scan: true
